services:
  backend:
    environment:
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORTA: ${SMTP_PORTA:-1025}
      SMTP_USAR_TLS: ${SMTP_USAR_TLS:-false}
      SMTP_USUARIO: ${SMTP_USUARIO:-}
      SMTP_SENHA: ${SMTP_SENHA:-}
      EMAIL_REMETENTE: "${EMAIL_REMETENTE:-Simple Mark <nao-responder@simplemark.local>}"
    depends_on:
      mailpit:
        condition: service_started

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
